name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure git
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"

      - name: Force push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hub https://$HF_TOKEN@huggingface.co/spaces/aycu2004/HF_play
          git push hub HEAD:main --force
